WelcomeMessage: "Welcome %player% to the server! Prepare to teleport"
Zones:
  "Zone One":
    x1: 100
    z1: 100
    x2: 200
    z2: 200
  "Zone Two":
    x1: 300
    z1: 300
    x2: 400
    z2: 400